# Generated by Django 5.0.7 on 2024-07-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='auth',
            new_name='author',
        ),
    ]
